### ISSUE TITLE
enviroCar Migration

### ISSUE THREAD

**Issue by autermann** [enviroCar/architecture#1]
- [x] VM aufsetzen  @EHJ-52n (und @christo52n )
  - [x] Konfiguration wie bisher
  - [x] Docker einrichten
  - [x] Munin-Docker-Plugins von processing.envirocar.org kopieren
- [x] Firewall
  - [x] processing.envirocar.org anpassen @christo52n
    - [x] `9092` für envirocar.org öffnen @christo52n
  - [x] envirocar.org @christo52n
    - [x] Docker Registry (`:5000`) freigeben an 52n_office und evtl. build.dev.52north.org @christo52n
    - [x] `80` und `443` für alle öffnen @christo52n
  - [x] old.envirocar.org @christo52n
    - [x] Port `22` auf altem Server für neuen Server öffnen @christo52n
- [x]  Dockerisierung der vorhandenen Komponenten finalisieren @autermann 
  - [x] Stable API @autermann 
  - [x] Dev API @autermann 
  - [x] Anonymous API @autermann 
  - [x] Docker Registry @autermann 
  - [x] Proxy (Caddy) @autermann 
  - [x] Landingpage  @autermann 
  - [x] Webapp @autermann 
  - [x] Auth Proxy @autermann 
  - [x] citram.de @autermann 
  - [x] 2x MongoDB @autermann 
- [x] App im Zusammenspiel mit Read-Only-Mode ausprobieren @autermann @dewall 
- [x] Backup-Konzept erarbeiten @EHJ-52n @autermann 
- [x] Backup-Konzept implementieren @EHJ-52n @autermann 
- [x] Migration
  - [x] Downtime abschätzen @autermann 
  - [x] Announcement (CITRAM community & enviroCar mailing list) @ahitch
  - [x] Activate Read-Only @autermann https://github.com/enviroCar/enviroCar-server/pull/254
  - [x] Copy database `enviroCar` @autermann 
  - [x] Copy database `enviroCarTesting` @autermann 
  - [x] Domain (envirocar.org & citram.de) umschalten (@christo52n )
  - [x] Let's Encrypt Zertifikate erstellen @autermann
- [x] GeoEvent Server überprüfen und deaktivieren (ags.52north.org) @EHJ-52n
- [x] build.dev.52north.org anpassen @EHJ-52n @autermann

**Comment by autermann** [comment]
```sh
ssh envirocar.org mongodump --db=enviroCar --archive | docker exec mongo-stable mongorestore --archive
```

Takes around 75 minutes.

**Comment by autermann** [comment]
```sh
#!/bin/bash

set -e

DIRECTORY=/backup/preliminary/docker/mongodb
LABEL=org.envirocar.backup.mongodb

mkdir -p "${DIRECTORY}"

docker ps --format "{{.ID}} {{.Names}} {{.Label \"${LABEL}\"}}" --filter "label=${LABEL}" | 
while read id name database; do
  echo "[$(date)] Dumping Mongo database ${database} of ${id} to ${name}.gz" >&2
  docker exec ${id} mongodump --db  ${database} --gzip --archive >  "${DIRECTORY}/${name}.gz"
done 
```

**Comment by autermann** [comment]
```shell
#!/bin/bash
set -e

DIRECTORY=/backup/preliminary/docker/volumes
LABEL='org.envirocar.backup'

mkdir -p "${DIRECTORY}"

docker volume ls -f "LABEL=${LABEL}=true" -f 'driver=local' --format '{{.Name}} {{.Mountpoint}}' | 
  while read volume mount; do 
    echo "[$(date)] Backing up Volume: ${volume}" >&2

    containers=$(docker ps --format '{{.Names}}' --filter "volume=${volume}")
    if [ ${#containers} -gt 0 ]; then
      echo "[$(date)] Pausing containers: ${containers[@]}" >&2
      docker pause ${containers[@]}
    fi
    
    rsync "${mount}" "${DIRECTORY}/${volume}"

    if [ ${#containers} -gt 0 ]; then
      echo "[$(date)] Unpausing containers: ${containers[@]}" >&2
      docker unpause ${containers[@]}
    fi
  done
```

**Comment by EHJ-52n** [comment]
@autermann Ist der Punkt

>   - [ ] (Weiterleitung an neuen Server) @EHJ-52n 

noch notwendig?

**Comment by autermann** [comment]
Nein

**Comment by autermann** [comment]
```sh
#!/bin/bash

set -e

DIRECTORY=/backup/preliminary/docker/postgres
LABEL=org.envirocar.backup.postgres

mkdir -p "${DIRECTORY}"

docker ps --format "{{.ID}} {{.Names}} {{.Label \"${LABEL}\"}}" --filter "label=${LABEL}" | 
while read id name label; do
  IFS=',' read -ra tables <<<"${label}"
  for table in ${tables[@]}; do 
    filename="${DIRECTORY}/${name}_${table}.gz"
    echo "[$(date)] Dumping Postgres table ${table} of ${name} to ${filename}" >&2
    [ -e "${filename}" ] && rm "${filename}"
    docker exec ${id} sh -c "PGPASSWORD=\"\${POSTGRES_PASSWORD}\" pg_dump -d "\${POSTGRES_DB}" -U "\${POSTGRES_USER}" -E UTF-8 -F plain -t ${table} ${database}" | gzip > "${filename}"
  done
done 
```

**Comment by EHJ-52n** [comment]
Das Backup-Konzept ist implementiert und muss nächste Woche bezügl. Speicherverbrauch verifiziert werden, damit uns über die Weihnachtsfeiertage nicht die Festplatten voll laufen.

**Comment by autermann** [comment]
> GeoEvent Server überprüfen und deaktivieren (ags.52north.org)

@EHJ-52n wie sieht es damit aus?
